name: 'AZola Deploy to Pages'
description: 'Build and deploy a modified Zola site to GitHub Pages'
author: 'Andy Berdan'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zap'  
  color: 'green'
